# Generated by Django 2.2.3 on 2019-07-03 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='equipamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_equipamento', models.CharField(max_length=254)),
                ('categoria_equipamento', models.CharField(max_length=240)),
                ('quantidade_equipamento', models.PositiveIntegerField()),
            ],
        ),
    ]
